In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from scipy import sparse


ImportError: DLL load failed while importing ft2font: The specified module could not be found.

In [6]:
ratings = pd.read_csv('toy_dataset.csv',index_col=0)
ratings.head()

action1  action2  action3  romantic1  romantic2  romantic3
user 1      4.0      5.0      3.0        NaN        2.0        1.0
user 2      5.0      3.0      3.0        2.0        2.0        NaN
user 3      1.0      NaN      NaN        4.0        5.0        4.0
user 4      NaN      2.0      1.0        4.0        NaN        3.0
user 5      1.0      NaN      2.0        3.0        3.0        4.0

In [7]:
ratings = ratings.fillna(0)

In [8]:
ratings

action1  action2  action3  romantic1  romantic2  romantic3
user 1      4.0      5.0      3.0        0.0        2.0        1.0
user 2      5.0      3.0      3.0        2.0        2.0        0.0
user 3      1.0      0.0      0.0        4.0        5.0        4.0
user 4      0.0      2.0      1.0        4.0        0.0        3.0
user 5      1.0      0.0      2.0        3.0        3.0        4.0

In [14]:
def standardize(row):
    new_row = (row - row.mean())/(row.max()-row.min())
    return new_row

ratings_std = ratings.apply(standardize)
ratings_std
    


action1  action2   action3  romantic1  romantic2  romantic3
user 1     0.36      0.6  0.400000      -0.65      -0.08      -0.35
user 2     0.56      0.2  0.400000      -0.15      -0.08      -0.60
user 3    -0.24     -0.4 -0.600000       0.35       0.52       0.40
user 4    -0.44      0.0 -0.266667       0.35      -0.48       0.15
user 5    -0.24     -0.4  0.066667       0.10       0.12       0.40

NameError: name 'standardize' is not defined

NameError: name 'cosine_similarity' is not defined

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
item_similarity = cosine_similarity(ratings_std.T)
print(item_similarity)

[[ 1.          0.70668875  0.81368151 -0.79941088 -0.02539184 -0.91410609]
 [ 0.70668875  1.          0.72310153 -0.84515425 -0.5189993  -0.84337386]
 [ 0.81368151  0.72310153  1.         -0.84794611 -0.3799803  -0.80218063]
 [-0.79941088 -0.84515425 -0.84794611  1.          0.14803913  0.72374686]
 [-0.02539184 -0.5189993  -0.3799803   0.14803913  1.          0.39393939]
 [-0.91410609 -0.84337386 -0.80218063  0.72374686  0.39393939  1.        ]]


In [28]:
item_similarity_df = pd.DataFrame(item_similarity,index=ratings.columns,columns=ratings.columns)

In [29]:
item_similarity_df

action1   action2   action3  romantic1  romantic2  romantic3
action1    1.000000  0.706689  0.813682  -0.799411  -0.025392  -0.914106
action2    0.706689  1.000000  0.723102  -0.845154  -0.518999  -0.843374
action3    0.813682  0.723102  1.000000  -0.847946  -0.379980  -0.802181
romantic1 -0.799411 -0.845154 -0.847946   1.000000   0.148039   0.723747
romantic2 -0.025392 -0.518999 -0.379980   0.148039   1.000000   0.393939
romantic3 -0.914106 -0.843374 -0.802181   0.723747   0.393939   1.000000

In [32]:
def get_similar_movies(movie_name,user_rating):
    similar_score = item_similarity_df[movie_name]*(user_rating-2.5)
    similar_score = similar_score.sort_values(ascending=False)
    
    return similar_score

print(get_similar_movies("romantic3",1))

action1      1.371159
action2      1.265061
action3      1.203271
romantic2   -0.590909
romantic1   -1.085620
romantic3   -1.500000
Name: romantic3, dtype: float64


In [36]:
MCU_lover = [("action1",5),("action3",4),("romantic1",1)]
similar_movies = pd.DataFrame()
for movie,rating in MCU_lover:
    similar_movies = similar_movies.append(get_similar_movies(movie,rating))
    
    

In [37]:
similar_movies.head()

action1   action2   action3  romantic1  romantic2  romantic3
action1    2.500000  1.766722  2.034204  -1.998527  -0.063480  -2.285265
action3    1.220522  1.084652  1.500000  -1.271919  -0.569970  -1.203271
romantic1  1.199116  1.267731  1.271919  -1.500000  -0.222059  -1.085620